services:
    db:
        image: mysql:8.0
        container_name: mysql-ledger
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password123
            MYSQL_DATABASE: ledger_db
        volumes:
            - ./mysql/data:/var/lib/mysql
